### ISSUE TITLE
Do poprawy :)

### ISSUE THREAD

**Issue by kacgrzes** [mraq1234/mod11#2]
- [x] `connectDragPreview(connectDropTargetLane(connectDropTargetNote` to mi troche nie pasuje. Poczytaj na temat `compose` w JS. Na początek odsyłam [tutaj](https://medium.com/@dtipson/creating-an-es6ish-compose-in-javascript-ac580b95104a)
- [x] nie używaj skrótów w nazwach zmiennych (np.`drgIco` spokojnie można nazwać `dragIcon` a nie musiałbym się zastanawiać co oznacza ten szyfr). Dalej: `srcIdx` -> `sourceIndex`, `trgIdx` -> `targetIndex`
- [x] Zamiast `object.assign` używaj operatora `spread` (`...`) na obiekcie. Więcej na ten temat [tutaj](http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html)
- [x] używasz niektórych zmiennych tylko raz np. `lineNotesArray`. Poza tym sufix `Array` jest tutaj zbędny. Wystarczy samo `lineNotes`.
- [x] arrow function nie musi zwracać JSX w nawiasach i ze słowem kluczowym `return`. Zamiast pisać:
``` js
() => { return (<div></div>) }
```
można śmiało zrobić:
``` js
() => <div></div>
```

**Comment by mraq1234** [comment]
- [x] `connectDragPreview(connectDropTargetLane(connectDropTargetNote` to mi troche nie pasuje. Poczytaj na temat `compose` w JS. Na początek odsyłam [tutaj](https://medium.com/@dtipson/creating-an-es6ish-compose-in-javascript-ac580b95104a)

- Zrobione - poszedłem na łatwiznę i wykorzystałem flowRight z Lodasha :)

- [x] nie używaj skrótów w nazwach zmiennych (np.`drgIco` spokojnie można nazwać `dragIcon` a nie musiałbym się zastanawiać co oznacza ten szyfr). Dalej: `srcIdx` -> `sourceIndex`, `trgIdx` -> `targetIndex`

- Nie wiem co mnie naszło ...

- [x] Zamiast `object.assign` używaj operatora `spread` (`...`) na obiekcie. Więcej na ten temat [tutaj](http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html)

- żadnego Object.assign tylko spread operator - uroczyście przyrzekam :))

- [x] używasz niektórych zmiennych tylko raz np. `lineNotesArray`. Poza tym sufix `Array` jest tutaj zbędny. Wystarczy samo `lineNotes`.

- Tam gdzie to możliwe oraz zauważyłem to się pozbyłem.

- [x] arrow function nie musi zwracać JSX w nawiasach i ze słowem kluczowym `return`.

- Wszędzie gdzie to możliwe pousuwane!

- Dodatkowo wywołanie callApi wyrzucone do akcji a w metodzie endDrop wywołana "zdispaczowana" akcja!
